# Generated by Django 5.0.6 on 2024-06-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicModel',
            fields=[
                ('musician_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('instrument', models.CharField(max_length=40)),
                ('musicians', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album_app.albummodel')),
            ],
        ),
    ]
