# Generated by Django 5.0.6 on 2024-06-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=100)),
                ('Album_release_Date', models.DateTimeField(auto_now=True, verbose_name='Release Date')),
                ('Album_Rating', models.IntegerField(choices=[(1, '1 '), (2, '2'), (3, '3 '), (4, '4'), (5, '5')], verbose_name='Rating')),
            ],
        ),
    ]
